### ISSUE TITLE
We could not found your streamer site!

### ISSUE THREAD

**Issue by muazzamazaz** [DanielnetoDotCom/YouPHPTube-Encoder#40]
After installation when I give streamer site url it throughs error while site exists and can be found here

http://cypherkiller.com/YouPHPTube-Encoder/
http://cypherkiller.com/YouPHPTube/

**Comment by gamersalpha** [comment]
i see this erro commes when user from youphptube go to youphptube-encoder
i have the same error.

**Comment by gamersalpha** [comment]
on my config : 

![image](https://user-images.githubusercontent.com/32466950/37565137-b9775d78-2aa3-11e8-8de8-c292c67de66a.png)


i have this

what's is wrong when i try to connect on my encoder site =

**Comment by muazzamazaz** [comment]
@DanielnetoDotCom 
Please see http://cypherkiller.com/YouPHPTube-Encoder/ I still have error

**Comment by muazzamazaz** [comment]
@gamersalpha 

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Encoder-Error-We-could-not-found-your-streamer-site!

Resolved the issue

**Comment by birdie60** [comment]
Unfortunately, I still have the same issue. I did follow the directives of the above link to Encoder Wiki.
What else could be the reason that my streamer site is not found?

**Comment by DanielnetoDotCom** [comment]
@birdie60 you need to share your log file

**Comment by birdie60** [comment]
@DanielnetoDotCom 
Thx for your care - highly appreciated! Let me provide you with all the symptoms I encounter.

The only line in my YPT logfile since I installed and configured my own encoder is, repeatedly:
`[30-Mar-2018 10:18:30 Europe/Vienna] Class Plugin Not found: /YouPHPTube/pluginsAvailable.json`

On all my YouPHPTube pages I get this:
`Warning: file_get_contents(http://doku.vogelschau.com/YouPHPTube/plugin/CustomizeAdvanced/advancedCustom.json.php): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden in /home/vogel5/public_html/doku/YouPHPTube/view/include/navbar.php on line 11`

I installed a PHPInfo.php script on the YouPHPTube site, and it says:
```
allow_url_fopen = On
allow_url_include = On
```
I have bought and installed your MP4ThumbsAndGif plugin, but when I uploaded a .mp4 in YouPHPTube (not in Encoder), no thumbnails and GIFs were created.

And I still have this "Sorry! We could not found your Streamer Site" in Encoder, whenever I want to log in.

Strange -

**Comment by DanielnetoDotCom** [comment]
I bet you guys are using cpanel, I have faced this issue before. 

you change the php.ini file but file_get_contents for external content keeping not working.

You must find a way to enable it.
I am not cpanel expert (I don't like cpanel), but there is a way to change the php.ini file for a single site only. I think that is the key.

**Comment by Thuaf** [comment]
My Fixed :) 
www.site.com/tube
www.site.com/encoder
problem couldnt site
my fix
www.site.com/tube
www.site2.com/encoder

and new apache location try not tested...

**Comment by gamersalpha** [comment]
Hello if y have a bda ssl certificat, not working, i have no choice to have a good certificat ssl to make it works

**Comment by DanielnetoDotCom** [comment]
If you dont have a good SSL, use http instead https

**Comment by Thuaf** [comment]
Realy fixed no ssl problem
 and no english language  fix 1.  2 hosting and ip tested 
Fix 2 site.com/tube site.com/encoder install and go phpmyadmin go encoder go configurations allowedstreamersurl null  go site.com/encoder please sign http and https://localhost/encoder streamer site user and password worked tested real worked

**Comment by DanielnetoDotCom** [comment]
sorry, I cant not understand
